[package]
name = "mesos"
version = "0.1.0"
authors = ["Connor Doyle <connor@mesosphere.io>"]
# links = "mesos"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
lazy_static = "0.1.14"
libc = "0.1"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"
